<?php

namespace krivobokruslan\fayechat\forms;

use yii\helpers\ArrayHelper;
use krivobokruslan\fayechat\entities\Room;
use yii\base\Model;
use krivobokruslan\fayechat\entities\User;

class RoomForm extends Model
{
    public $title;
    private $owner;
    public $members = [];

    public function __construct(Room $room = null, array $config = [])
    {
        parent::__construct($config);
        if ($room) {
            $this->title = $room->title;
            $this->members = ArrayHelper::getColumn($room->membersAssignments, 'user_id');
        }
    }

    public function rules()
    {
        return [
            [['title', 'members'], 'required'],
            [['title'], 'string'],
            [['members'], 'each', 'rule' => [
                'exist', 'targetClass' => User::class, 'targetAttribute' => 'id'
            ]
            ],
            [['title'], 'filter', 'filter' => function ($value) {
                return strip_tags($value);
            }]
        ];
    }

    public function addOwner($userId)
    {
        $this->owner = $userId;
    }

    public function beforeValidate()
    {
        $this->members[] = $this->owner;
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}